name: Build and deploy

on:
  push:
    branches-ignore:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
      env:
        CI: false
    - name: npm build
      run: |
            npm run build
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            ls -lR dst
      env:
        CI: false
    - name: Deploy
