name: Build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-hub/gcloud@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
      env:
        CI: false
    - name: npm build
      run: |
            npm run build
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            pwd
            echo '***************************************************************************************************'
            ls -lRd dst
      env:
        CI: false
    - name: Deploy
      env:
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
        args: app deploy dst/app.yaml